### ISSUE TITLE
Fix the missing logic in the new simulator fixes

### ISSUE THREAD

**Issue by tonilastre** [memgraph/orb#87]
Complete and fix the simulator (branch `fix/new-simulator`):

* Remove useless flag `isRenderCalledByUser`. Check if the flag `isSimulationAnimated` is used at all and remove it if needed.
* Fix and remove TODOs in graph model, simulator engine, and views (which connects model and simulator)

**Comment by AlexIchenskiy** [comment]
The `isSimulationAnimated` flag is used to enable or disable the simulation animation. It is enabled by default, and by disabling it, the graph will appear in its final position without moving nodes by the physics engine. However, it does not work in the current version. It can be easily fixed by preventing the simulation from rendering while in progress, but the animation will still be present while dragging nodes or zooming. Is it better to completely remove it or to maintain this fix?

**Comment by tonilastre** [comment]
I would say that let's remove it, we can always add it later on.
